# Generated by Django 4.1.7 on 2023-11-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
